# Generated by Django 5.0.6 on 2024-07-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_task_type_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(related_name='task', to='webapp.type', verbose_name='Тип'),
        ),
    ]
