# Generated by Django 5.0.6 on 2024-07-15 17:46

import webapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('created_date', models.DateField(verbose_name='Дата создания')),
                ('updated_date', models.DateField(blank=True, null=True, verbose_name='Дата обновления')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[webapp.models.description_valid], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=50, validators=[webapp.models.summary_valid], verbose_name='Краткое описание'),
        ),
    ]
